#!/bin/bash

clear

cores=`grep -c ^processor /proc/cpuinfo`
# cores=`/usr/bin/nproc --all`
echo "This container can use up to $cores cores"
read -p 'How many would you like to use? ' corechoice
export CORECHOICE=$corechoice
echo "- - - - - - - - - - - - - - - - - - - -"
echo ""
time /usr/bin/env python3 /calculate-pi.py
